### ISSUE TITLE
Weekly scrum – [February 27 to March 6]

### ISSUE THREAD

**Issue by abungay** [amazin-team/Amazin-online-bookstore#1]
Please comment on this issue with answers the following questions:
- what have I done this week?
- what will I do next week?
- what is holding me back? (if applicable)

Expected length: 1-2 sentences per item.

**Comment by LauraMachado21** [comment]
This week: Created Trello Board & Sprint Planning
Next week: Implement shopping cart and inventory

**Comment by zaidoon1** [comment]
This week: Created the end points as well as a basic view that allows user to create, edit, delete a book. The user is also able to view all books created.
Next week: Implement Search functionality for books

**Comment by MohamedZalat** [comment]
This week: Added utility test base class with protected method to assist with unit tests and integration tests. Added all unit tests.
Next week: Implement integration tests.

**Comment by abungay** [comment]
This week: Updated README, added ER and UML diagrams, UI changes for styling, formatting, and grammar for HTML pages and forms.
Next week: Create User Model with different User and BookStoreOwner roles, login and registration pages.
