### ISSUE TITLE
Non-production deployments for testing

### ISSUE THREAD

**Issue by abungay** [amazin-team/Amazin-online-bookstore#11]
It would facilitate our Pull Request process if we had deployments for branches other than master to help the reviewers test the UI changes without having to pull them locally and run it for each PR.

These deployments would go to either github deployments or heroku on a separate URL than the one we are using for our master branch on heroku.

**Comment by Hajar1** [comment]
This is out of scope for the project

**Comment by abungay** [comment]
If we do decide to do this at a later point in time this article may be helpful: https://devcenter.heroku.com/articles/multiple-environments
