### ISSUE TITLE
Weekly scrum – [March 6 to March 13]

### ISSUE THREAD

**Issue by zaidoon1** [amazin-team/Amazin-online-bookstore#16]
Please comment on this issue with answers the following questions:

- what have I done this week?
- what will I do next week?
- what is holding me back? (if applicable)

Expected length: 1-2 sentences per item.

**Comment by zaidoon1** [comment]
- what have I done this week? Added back-end and front-end validation
- what will I do next week? Searching for books (back-end)
- what is holding me back? N/A

**Comment by abungay** [comment]
This week: Add github pull request template file, create wiki page to explain how to update diagrams, create Kanban board so we can switch over from Trello, reviewing & testing PRS, starting to work on backend for User Login/Authentication
Next week: Finish User Login/Authentication backend with unit & integration tests, integrate backend with User login & registration UI pages.

**Comment by LauraMachado21** [comment]
This week:
- Incorporated sb-admin template
- Moved kanban board from Trello to GitHub
- Added login, registration and updated error page

Next week:
- Develop shopping cart

**Comment by MohamedZalat** [comment]
This week:
Reviewed merge requests
Looked at integrating postgresql to the project
Next week:
Integrate postgresql with project

**Comment by Hajar1** [comment]
This week:

- Fixed bug on the input fields
- templated data table
- Created application controller
- Created fragment controller
- Added Jquery Table
- Decoupled Index from one page two multi pages
- Revamped the CSS Style sheet
