### ISSUE TITLE
Replace the H2 database with Postgres database

### ISSUE THREAD

**Issue by zaidoon1** [amazin-team/Amazin-online-bookstore#17]
We are currently using the H2 database, however, since this is an in memory database and we are using Heroku, all the data stored in the database is deleted once the dynos of Heroku go to sleep due to inactivity (we are using the free version of Heroku). Therefore, we need to switch to a disk-optimized database (Postgres).

**Comment by MohamedZalat** [comment]
Currrently it is implemented in pull request #52  but postgresql is not setup on Heroku yet.
