### ISSUE TITLE
Weekly scrum - [March 13 to March 20]

### ISSUE THREAD

**Issue by LauraMachado21** [amazin-team/Amazin-online-bookstore#34]
Please comment on this issue with answers the following questions:

- what have I done this week?
- what will I do next week?
- what is holding me back? (if applicable)

Expected length: 1-2 sentences per item.

**Comment by Hajar1** [comment]
This week:

- Added Travis CI to README
- Created application Logo and added it to readme and navbar
- fixed styling bugs 
- fixed logo location
- Almost finished the implementation of s3 storage of pictures

Next week:
- finish s3 storage implementation

**Comment by zaidoon1** [comment]
- what have I done this week? Searching for books (back-end)
- what will I do next week? Add more integration tests and TBD
- what is holding me back? N/A

**Comment by abungay** [comment]
what have I done this week: UI fixes, styling, pull request reviews and testing, initial user login authenticaiton in the backend and connection with the frontend login pages
what will I do next week: Add more integration tests, unit tests, add support for forgot-password, and admin-registration

**Comment by MohamedZalat** [comment]
This week:
- Integrated postgresql
Next week:
- Book recommendations
Depends:
- User model and oauth
