### ISSUE TITLE
Ability to save book picture

### ISSUE THREAD

**Issue by LauraMachado21** [amazin-team/Amazin-online-bookstore#41]

**Comment by abungay** [comment]
Along with this issue we also need to figure out where we will display the image for the book.

Will the user click on the name of the book to go to the 'view' page for this book? Or will we display just a small version of the book image inline in the JQuery Table we currently have?

**Comment by zaidoon1** [comment]
the easiest would be to add a picture column, something that would be better would be to remove the jquery table, and have a catalogue of book covers, then when you click on each book, you get more info, as well as the ability to edit or delete. However, I don't think we will have time for this so a picture column would have to do for now

**Comment by zaidoon1** [comment]
Fixed in #98
