### ISSUE TITLE
Weekly scrum - [March 20 to March 27]

### ISSUE THREAD

**Issue by MohamedZalat** [amazin-team/Amazin-online-bookstore#59]
Please comment on this issue with answers the following questions:

- what have I done this week?
- what will I do next week?
- what is holding me back? (if applicable)

Expected length: 1-2 sentences per item.

**Comment by zaidoon1** [comment]
- what have I done this week? Added search functionality to the front-end
- what will I do next week? Clean up create book and update book page
- what is holding me back? N/A

**Comment by abungay** [comment]
- what have I done this week? Fixing bugs, refactoring, and testing for User authentication - login, logout, registration.
- what will I do next week? Add support for forgot-password, admin registration, and refactor page header into fragment.
- what is holding me back? N/A

**Comment by LauraMachado21** [comment]
- Done this week: Creating the shopping cart UI
- What will I do next week: Add shopping cart back-end & checkout functionality
- what is holding me back? N/A

**Comment by MohamedZalat** [comment]
What have I dont this week? Reviewed merge requests.
What will I do next week? Add book recommendations.
What is holding me back? User authentication and shopping cart.

**Comment by Hajar1** [comment]
* Done this week: fragmented the ui items and worked on S3 storage
* what will i do next week: S3 storage full implementation, work on the GUI, and fix the Shopping cart
* What is holding me back? @LauraMachado21  and @MohamedZalat
