### ISSUE TITLE
Weekly scrum - [March 27 to April 3]

### ISSUE THREAD

**Issue by Hajar1** [amazin-team/Amazin-online-bookstore#64]
Please comment on this issue with answers the following questions:

what have I done this week?
what will I do next week?
what is holding me back? (if applicable)
Expected length: 1-2 sentences per item.

**Comment by zaidoon1** [comment]
what have I done this week? Cleaned up create book and update book page, allow anonymous viewing of books.
what will I do next week? Nothing, the project ended.
what is holding me back? (if applicable) N/A

**Comment by abungay** [comment]
what have I done this week? Display currently logged in user on top of page header, update user email validation regex, review PRs.
what will I do next week? Nothing, the project ended.
what is holding me back? (if applicable) N/A

**Comment by LauraMachado21** [comment]
- what have I done this week? Completed shopping-cart functionality & checkout 
- what will I do next week: adding additional tests
- what is holding me back? (if applicable) N/A

**Comment by Hajar1** [comment]
* Added Book Viewer
* Added Book Shower 
* Added Admin.html

* Refactored index.html
* Added S3 integration

**Comment by MohamedZalat** [comment]
What have I done this week? Book recommendations.
What will I do next week? Add test cases.
What is holding me back? N/A
